name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-test:
    runs-on: macos-14

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Run tests
        run: swift test --parallel